### ISSUE TITLE
some updates

### ISSUE THREAD

**Issue by Apollo1840** [morphism90/DeepECG#3]
This is a wonderful repo!

But the author of this repo seems to not update this for a long time. I guess he deprecated this. So I forked it and made some updates: 

- big refactoring
- removing draft part
- grouping reused methods
- separating model architects
- ....

Since the refactoring is big, so I did not create PR. 

Feel free to visit and review my code, but cite the original paper from this authors' repo: https://github.com/Apollo1840/deepECG

**Comment by ismorphism** [comment]
Thanks for your comment! I'm thinking to wake this repo up :-)
